"""add quality metrics to transcriptions

Revision ID: 30d597926a9c
Revises: 
Create Date: 2026-04-25 17:22:05.347366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d597926a9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptions', sa.Column('total_segments', sa.Integer(), nullable=True))
    op.add_column('transcriptions', sa.Column('total_chars', sa.Integer(), nullable=True))
    op.add_column('transcriptions', sa.Column('estimated_words', sa.Integer(), nullable=True))
    op.add_column('transcriptions', sa.Column('avg_logprob', sa.Float(), nullable=True))
    op.add_column('transcriptions', sa.Column('repetition_rate', sa.Float(), nullable=True))
    op.add_column('transcriptions', sa.Column('chars_per_minute', sa.Float(), nullable=True))
    op.add_column('transcriptions', sa.Column('language_confidence', sa.Float(), nullable=True))
    op.add_column('transcriptions', sa.Column('hallucination_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcriptions', 'hallucination_flag')
    op.drop_column('transcriptions', 'language_confidence')
    op.drop_column('transcriptions', 'chars_per_minute')
    op.drop_column('transcriptions', 'repetition_rate')
    op.drop_column('transcriptions', 'avg_logprob')
    op.drop_column('transcriptions', 'estimated_words')
    op.drop_column('transcriptions', 'total_chars')
    op.drop_column('transcriptions', 'total_segments')
    # ### end Alembic commands ###
