"""add speakers and speaker_embeddings tables

Revision ID: 840f682f81f6
Revises: 30d597926a9c
Create Date: 2026-04-25 19:00:26.186845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840f682f81f6'
down_revision: Union[str, Sequence[str], None] = '30d597926a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speakers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_host', sa.Boolean(), nullable=True),
    sa.Column('voice_embedding', sa.Text(), nullable=True),
    sa.Column('embedding_count', sa.Integer(), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=True),
    sa.Column('first_seen_episode', sa.String(), nullable=True),
    sa.Column('last_seen_episode', sa.String(), nullable=True),
    sa.Column('total_appearances', sa.Integer(), nullable=True),
    sa.Column('enrollment_episodes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('speaker_embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.Column('episode_id', sa.String(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speaker_embeddings')
    op.drop_table('speakers')
    # ### end Alembic commands ###
