"""add indexed flag to episodes

Revision ID: 8be932462edf
Revises: bc514fe7ccb8
Create Date: 2026-04-29 22:03:34.365412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8be932462edf'
down_revision: Union[str, Sequence[str], None] = 'bc514fe7ccb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('indexed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodes', 'indexed')
    # ### end Alembic commands ###
