"""add diarized flag to episodes

Revision ID: c38b9b81ea89
Revises: 840f682f81f6
Create Date: 2026-04-26 16:31:43.100210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c38b9b81ea89'
down_revision: Union[str, Sequence[str], None] = '840f682f81f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('diarized', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodes', 'diarized')
    # ### end Alembic commands ###
